### PR TITLE
Dev/jchen/alternate reference versioning

### PR DESCRIPTION
**Pull request by Jackychen-bluescape**
Mechanism to alternate between v2 and v3 reference section.

Note: static content for v2 reference is subject to change.

### CODE REVIEW

**Comment by Codiegladney-bluescape** [comment]
Shouldn't the "versioning-v2" page match what we see in the 3scale DevPortal? https://developer.us01.bluescape.com/reference/versioning

The only exception I think would be to remove the hyperlinks to /v1/ and /v0/ 
- I think should still keep the "Version" table on that page, mentioning /v1/ and /v0/ as discontinued, just no hyperlink.

Thoughts? @Jackychen-bluescape @NoahBluescape

**Comment by Jackychen-bluescape** [comment]
I was considering to leave v0 and v1 in the versioning-v2 page, but I couldn't think of any reasons why it'll be relevant since they no longer re-direct anywhere.

**Comment by Codiegladney-bluescape** [comment]
> I was considering to leave v0 and v1 in the versioning-v2 page, but I couldn't think of any reasons why it'll be relevant since they no longer re-direct anywhere.

The reasons I think we should keep it:
A) for historical context (doesn't hurt)
B) Because the content below the versioning table references /v1/ repeatedly, so it makes sense to me to list it in the table, along with its Discontinued date.

**Comment by Jackychen-bluescape** [comment]
> > I was considering to leave v0 and v1 in the versioning-v2 page, but I couldn't think of any reasons why it'll be relevant since they no longer re-direct anywhere.
> 
> The reasons I think we should keep it:
> A) for historical context (doesn't hurt)
> B) Because the content below the versioning table references /v1/ repeatedly, so it makes sense to me to list it in the table, along with its Discontinued date.

Oh yes, you're right. I overlooked the /v1/ references. I'll add them back to the versioning table :)

**Comment by Jackychen-bluescape** [comment]
@Codiegladney-bluescape @NoahBluescape @vlad-bluescape any additional comments/suggestions regarding this PR? Safe to merge?

**Comment by Codiegladney-bluescape** [comment]
> @Codiegladney-bluescape @NoahBluescape @vlad-bluescape any additional comments/suggestions regarding this PR? Safe to merge?

@Jackychen-bluescape I would remove the hyperlink from /v1/ and /v0/ on the "Versions" table. I'd make them plain text instead

**Comment by Jackychen-bluescape** [comment]
> > @Codiegladney-bluescape @NoahBluescape @vlad-bluescape any additional comments/suggestions regarding this PR? Safe to merge?
> 
> @Jackychen-bluescape I would remove the hyperlink from /v1/ and /v0/ on the "Versions" table. I'd make them plain text instead

Sounds good.

**Review by Codiegladney-bluescape — APPROVED** [review]
LGTM

**Pull request merged**
